[[personal]]

////
á=&#225; é=&#233; í=&#237; ó=&#243; ú=&#250;

A=&#193; E=&#201; I=&#205; O=&#211; U=&#218;

n=&#241; N=&#209;
////

== link:index.html[PERSONAL]

*AMIGOS*

* EDWIN CASTELLANOS - CEL:316-2421466


*CONTACTOS PERSONALES*

* FABIO GARCIA CEL: 316-6950388 - 316-5313606 - Calle 11C # 73-52


*CONTACTOS COMERCIALES*

* LFL AUDIO - LUIS FERNANDO LOPEZ CEL:314-4843755 - lflaudiobose@hotmail - Cra 12 No. 84-12 Local 1 Esquina Tels: 6220668 - 5301850

* http://controlhobby.com/[http://controlhobby.com/ - Modelos Profesionales a Escala]

* TODO CAMARAS - ALFONSO PATI&#209;O - Cra 16 No.65-165 B. La Victoria - Tel:6475196 Cel:315-2870647

* JUAN VICENTE FLOREZ RINCON CELS:310-2753108, 316-3594221, 300-2666602 - juanvicenteflorezr@hotmail.com

** Asesor Juridico Financiero en Seguros: Vida, Salud, Automoviles, Cumplimiento, Generales, Escolares


*CONTACTOS SALUD*

* HEBERTH GARCIA RINCON - Medicina Biologica - Consultorio: Calle 63 No. 30-41, Bucaramanga tel:6474349, cel:315-3740121 - heberthneural@hotmail.com

* GABRIEL QUINTERO - QUIROPRACTICA - Cra 36 No. 42-02 Consultorio 301 Tel:6325071 Cel:316-5522947 mail:quiros64@yahoo.com

* DR. CAMILO ANDRES LARA MUÑOZ EXALUMNO? - Cra 34 #51-97 Tel:6850043 Cabecera - LA ISLA Local 9-18/9-19 Piso 2 Tel:644-4033


*DECLARACION DE RENTA*

* http://www.dian.gov.co/lamejorseleccion/[http://www.dian.gov.co/lamejorseleccion/ - Declarar Renta]


*SALUD*

* GLISEMIA:28375742

. ANTES DEL DESAYUNO(80-120) - 2 HORAS DESPUES DEL DESAYUNO < 180

. ANTES DEL ALMUERZO < 140 - 2 HORAS DESPUES DEL ALMUERZO < 180

. ANTES DE LA COMIDA < 140 - 2 HORAS DESPUES DE LA COMIDA < 180

*VARIOS*

* https://www.lifemiles.com/indexes.aspx[lifemiles - 13411091455 - 13436443602]